### ISSUE TITLE
Store folders only. 

### ISSUE THREAD

**Issue by jaredbidlow** [M-Scott-Lassiter/Excel-VBA-Directory-Manager#3]
If this is not impossible in VBA method, a feature request: option to only store folders. Because of speed in large folders on network drives (related issue: https://github.com/M-Scott-Lassiter/VBA-Directory-Manager/issues/2), someone might only want the folders in the directory to show. There is no way currently to write this with the current class module.

**Comment by M-Scott-Lassiter** [comment]
I used this project within another project of mine [to catalog files](https://github.com/M-Scott-Lassiter/Excel-File-Cataloger). That project makes use of the OmittedPrefix capability in this class to omit folders I know in advance are going to be excessively large.

If you were to do this change, I'd recommend making a new boolean property, e.g. `FoldersOnly`. This would need to get referenced in the `FindFilesAndFolders()` and `FindSubFilesAndFolders()` methods.

Of note though, these work by looping through all of the files at that location. So I'm not sure if it would speed up large folders because it still has to go over everything and figure out if it is a file or folder. The end result would be a class that only has folders, but it would take the same amount of time to get there.

Another possibility, limit the depth of how many folders down you traverse?

**Comment by jaredbidlow** [comment]
My thought is to use a file scripting object for the top level folder you wish to traverse. This would be enabled with a Boolean. Every other folder would be looped through your method. This would reduce the time it would take to complete a folders-only scan in my case, since I can discern which folders have a lot of files. I only point at these folders, not folders above. Thus top level gets an FSO treatment, while lower levels get Dir. 

Right now pure FSO gets slow due to a sheer amount of folders (some empty). Pure Dir gets slow due to large number of files.

**Comment by jaredbidlow** [comment]
I realize this is a bit confusing

**Comment by M-Scott-Lassiter** [comment]
I haven't had a chance to look it over again. Have you tried modifying the script to see if it will work?
